development:
  adapter: postgresql
  encoding: unicode
  database: quick_tally_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quick_tally_test
  pool: 5
  password:
